/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealerRouteImport } from './routes/dealer'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DealerIndexRouteImport } from './routes/dealer/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as DealerWonRouteImport } from './routes/dealer/won'
import { Route as DealerBidsRouteImport } from './routes/dealer/bids'
import { Route as DealerActiveRouteImport } from './routes/dealer/active'
import { Route as AuthenticatedRapporterRouteImport } from './routes/_authenticated/rapporter'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedInkorgRouteImport } from './routes/_authenticated/inkorg'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as DealerCarsLeadIdRouteImport } from './routes/dealer/cars.$leadId'
import { Route as AuthenticatedLeadsNyRouteImport } from './routes/_authenticated/leads/ny'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads/$leadId'
import { Route as AuthenticatedInstallningarProfilRouteImport } from './routes/_authenticated/installningar/profil'
import { Route as AuthenticatedAdminTestLeadIntakeRouteImport } from './routes/_authenticated/admin/test-lead-intake'
import { Route as AuthenticatedAdminStageRulesRouteImport } from './routes/_authenticated/admin/stage-rules'
import { Route as AuthenticatedAdminSmsDebugRouteImport } from './routes/_authenticated/admin/sms-debug'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminOrphanSmsRouteImport } from './routes/_authenticated/admin/orphan-sms'
import { Route as AuthenticatedAdminGdprRouteImport } from './routes/_authenticated/admin/gdpr'
import { Route as AuthenticatedAdminFaktureringRouteImport } from './routes/_authenticated/admin/fakturering'
import { Route as AuthenticatedAdminExportsRouteImport } from './routes/_authenticated/admin/exports'
import { Route as AuthenticatedAdminDealersRouteImport } from './routes/_authenticated/admin/dealers'
import { Route as AuthenticatedAdminDataCleanupRouteImport } from './routes/_authenticated/admin/data-cleanup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio/status'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio/inbound'
import { Route as ApiPublicLeadsIntakeRouteImport } from './routes/api/public/leads/intake'
import { Route as ApiPublicLeadsLeadIdRouteImport } from './routes/api/public/leads/$leadId'
import { Route as ApiPublicHooksProcessStageJobsRouteImport } from './routes/api/public/hooks/process-stage-jobs'
import { Route as ApiPublicHooksProcessQueuedSmsRouteImport } from './routes/api/public/hooks/process-queued-sms'
import { Route as ApiPublicHooksCheckDueTasksRouteImport } from './routes/api/public/hooks/check-due-tasks'
import { Route as AuthenticatedRapporterSaljareUserIdRouteImport } from './routes/_authenticated/rapporter.saljare.$userId'
import { Route as AuthenticatedRapporterHandlareDealerIdRouteImport } from './routes/_authenticated/rapporter.handlare.$dealerId'
import { Route as AuthenticatedAdminSettingsTimingRouteImport } from './routes/_authenticated/admin/settings.timing'
import { Route as AuthenticatedAdminSettingsSmsTemplatesRouteImport } from './routes/_authenticated/admin/settings.sms-templates'
import { Route as AuthenticatedAdminSettingsSlaRouteImport } from './routes/_authenticated/admin/settings.sla'
import { Route as AuthenticatedAdminSettingsNotificationsRouteImport } from './routes/_authenticated/admin/settings.notifications'
import { Route as AuthenticatedAdminSettingsLeadScoreRouteImport } from './routes/_authenticated/admin/settings.lead-score'
import { Route as AuthenticatedAdminSettingsFollowupsRouteImport } from './routes/_authenticated/admin/settings.followups'
import { Route as AuthenticatedAdminSettingsExternalLinksRouteImport } from './routes/_authenticated/admin/settings.external-links'
import { Route as AuthenticatedAdminSettingsBillingRouteImport } from './routes/_authenticated/admin/settings.billing'
import { Route as AuthenticatedAdminMatchPreviewLeadIdRouteImport } from './routes/_authenticated/admin/match-preview.$leadId'
import { Route as AuthenticatedAdminFaktureringLaggTillRouteImport } from './routes/_authenticated/admin/fakturering.lagg-till'
import { Route as AuthenticatedAdminDealersDealerIdRouteImport } from './routes/_authenticated/admin/dealers.$dealerId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRoute = DealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerIndexRoute = DealerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealerRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DealerWonRoute = DealerWonRouteImport.update({
  id: '/won',
  path: '/won',
  getParentRoute: () => DealerRoute,
} as any)
const DealerBidsRoute = DealerBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => DealerRoute,
} as any)
const DealerActiveRoute = DealerActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => DealerRoute,
} as any)
const AuthenticatedRapporterRoute = AuthenticatedRapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInkorgRoute = AuthenticatedInkorgRouteImport.update({
  id: '/inkorg',
  path: '/inkorg',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DealerCarsLeadIdRoute = DealerCarsLeadIdRouteImport.update({
  id: '/cars/$leadId',
  path: '/cars/$leadId',
  getParentRoute: () => DealerRoute,
} as any)
const AuthenticatedLeadsNyRoute = AuthenticatedLeadsNyRouteImport.update({
  id: '/leads/ny',
  path: '/leads/ny',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstallningarProfilRoute =
  AuthenticatedInstallningarProfilRouteImport.update({
    id: '/installningar/profil',
    path: '/installningar/profil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTestLeadIntakeRoute =
  AuthenticatedAdminTestLeadIntakeRouteImport.update({
    id: '/test-lead-intake',
    path: '/test-lead-intake',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStageRulesRoute =
  AuthenticatedAdminStageRulesRouteImport.update({
    id: '/stage-rules',
    path: '/stage-rules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSmsDebugRoute =
  AuthenticatedAdminSmsDebugRouteImport.update({
    id: '/sms-debug',
    path: '/sms-debug',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrphanSmsRoute =
  AuthenticatedAdminOrphanSmsRouteImport.update({
    id: '/orphan-sms',
    path: '/orphan-sms',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGdprRoute = AuthenticatedAdminGdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFaktureringRoute =
  AuthenticatedAdminFaktureringRouteImport.update({
    id: '/fakturering',
    path: '/fakturering',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportsRoute =
  AuthenticatedAdminExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDealersRoute =
  AuthenticatedAdminDealersRouteImport.update({
    id: '/dealers',
    path: '/dealers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDataCleanupRoute =
  AuthenticatedAdminDataCleanupRouteImport.update({
    id: '/data-cleanup',
    path: '/data-cleanup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio/inbound',
  path: '/api/public/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsIntakeRoute = ApiPublicLeadsIntakeRouteImport.update({
  id: '/api/public/leads/intake',
  path: '/api/public/leads/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsLeadIdRoute = ApiPublicLeadsLeadIdRouteImport.update({
  id: '/api/public/leads/$leadId',
  path: '/api/public/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessStageJobsRoute =
  ApiPublicHooksProcessStageJobsRouteImport.update({
    id: '/api/public/hooks/process-stage-jobs',
    path: '/api/public/hooks/process-stage-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessQueuedSmsRoute =
  ApiPublicHooksProcessQueuedSmsRouteImport.update({
    id: '/api/public/hooks/process-queued-sms',
    path: '/api/public/hooks/process-queued-sms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckDueTasksRoute =
  ApiPublicHooksCheckDueTasksRouteImport.update({
    id: '/api/public/hooks/check-due-tasks',
    path: '/api/public/hooks/check-due-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRapporterSaljareUserIdRoute =
  AuthenticatedRapporterSaljareUserIdRouteImport.update({
    id: '/saljare/$userId',
    path: '/saljare/$userId',
    getParentRoute: () => AuthenticatedRapporterRoute,
  } as any)
const AuthenticatedRapporterHandlareDealerIdRoute =
  AuthenticatedRapporterHandlareDealerIdRouteImport.update({
    id: '/handlare/$dealerId',
    path: '/handlare/$dealerId',
    getParentRoute: () => AuthenticatedRapporterRoute,
  } as any)
const AuthenticatedAdminSettingsTimingRoute =
  AuthenticatedAdminSettingsTimingRouteImport.update({
    id: '/settings/timing',
    path: '/settings/timing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsSmsTemplatesRoute =
  AuthenticatedAdminSettingsSmsTemplatesRouteImport.update({
    id: '/settings/sms-templates',
    path: '/settings/sms-templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsSlaRoute =
  AuthenticatedAdminSettingsSlaRouteImport.update({
    id: '/settings/sla',
    path: '/settings/sla',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsNotificationsRoute =
  AuthenticatedAdminSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsLeadScoreRoute =
  AuthenticatedAdminSettingsLeadScoreRouteImport.update({
    id: '/settings/lead-score',
    path: '/settings/lead-score',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsFollowupsRoute =
  AuthenticatedAdminSettingsFollowupsRouteImport.update({
    id: '/settings/followups',
    path: '/settings/followups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsExternalLinksRoute =
  AuthenticatedAdminSettingsExternalLinksRouteImport.update({
    id: '/settings/external-links',
    path: '/settings/external-links',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsBillingRoute =
  AuthenticatedAdminSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMatchPreviewLeadIdRoute =
  AuthenticatedAdminMatchPreviewLeadIdRouteImport.update({
    id: '/match-preview/$leadId',
    path: '/match-preview/$leadId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaktureringLaggTillRoute =
  AuthenticatedAdminFaktureringLaggTillRouteImport.update({
    id: '/lagg-till',
    path: '/lagg-till',
    getParentRoute: () => AuthenticatedAdminFaktureringRoute,
  } as any)
const AuthenticatedAdminDealersDealerIdRoute =
  AuthenticatedAdminDealersDealerIdRouteImport.update({
    id: '/$dealerId',
    path: '/$dealerId',
    getParentRoute: () => AuthenticatedAdminDealersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/inkorg': typeof AuthenticatedInkorgRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/rapporter': typeof AuthenticatedRapporterRouteWithChildren
  '/dealer/active': typeof DealerActiveRoute
  '/dealer/bids': typeof DealerBidsRoute
  '/dealer/won': typeof DealerWonRoute
  '/dealer/': typeof DealerIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/data-cleanup': typeof AuthenticatedAdminDataCleanupRoute
  '/admin/dealers': typeof AuthenticatedAdminDealersRouteWithChildren
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/fakturering': typeof AuthenticatedAdminFaktureringRouteWithChildren
  '/admin/gdpr': typeof AuthenticatedAdminGdprRoute
  '/admin/orphan-sms': typeof AuthenticatedAdminOrphanSmsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/sms-debug': typeof AuthenticatedAdminSmsDebugRoute
  '/admin/stage-rules': typeof AuthenticatedAdminStageRulesRoute
  '/admin/test-lead-intake': typeof AuthenticatedAdminTestLeadIntakeRoute
  '/installningar/profil': typeof AuthenticatedInstallningarProfilRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads/ny': typeof AuthenticatedLeadsNyRoute
  '/dealer/cars/$leadId': typeof DealerCarsLeadIdRoute
  '/admin/dealers/$dealerId': typeof AuthenticatedAdminDealersDealerIdRoute
  '/admin/fakturering/lagg-till': typeof AuthenticatedAdminFaktureringLaggTillRoute
  '/admin/match-preview/$leadId': typeof AuthenticatedAdminMatchPreviewLeadIdRoute
  '/admin/settings/billing': typeof AuthenticatedAdminSettingsBillingRoute
  '/admin/settings/external-links': typeof AuthenticatedAdminSettingsExternalLinksRoute
  '/admin/settings/followups': typeof AuthenticatedAdminSettingsFollowupsRoute
  '/admin/settings/lead-score': typeof AuthenticatedAdminSettingsLeadScoreRoute
  '/admin/settings/notifications': typeof AuthenticatedAdminSettingsNotificationsRoute
  '/admin/settings/sla': typeof AuthenticatedAdminSettingsSlaRoute
  '/admin/settings/sms-templates': typeof AuthenticatedAdminSettingsSmsTemplatesRoute
  '/admin/settings/timing': typeof AuthenticatedAdminSettingsTimingRoute
  '/rapporter/handlare/$dealerId': typeof AuthenticatedRapporterHandlareDealerIdRoute
  '/rapporter/saljare/$userId': typeof AuthenticatedRapporterSaljareUserIdRoute
  '/api/public/hooks/check-due-tasks': typeof ApiPublicHooksCheckDueTasksRoute
  '/api/public/hooks/process-queued-sms': typeof ApiPublicHooksProcessQueuedSmsRoute
  '/api/public/hooks/process-stage-jobs': typeof ApiPublicHooksProcessStageJobsRoute
  '/api/public/leads/$leadId': typeof ApiPublicLeadsLeadIdRoute
  '/api/public/leads/intake': typeof ApiPublicLeadsIntakeRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/inkorg': typeof AuthenticatedInkorgRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/rapporter': typeof AuthenticatedRapporterRouteWithChildren
  '/dealer/active': typeof DealerActiveRoute
  '/dealer/bids': typeof DealerBidsRoute
  '/dealer/won': typeof DealerWonRoute
  '/': typeof AuthenticatedIndexRoute
  '/dealer': typeof DealerIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/data-cleanup': typeof AuthenticatedAdminDataCleanupRoute
  '/admin/dealers': typeof AuthenticatedAdminDealersRouteWithChildren
  '/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/admin/fakturering': typeof AuthenticatedAdminFaktureringRouteWithChildren
  '/admin/gdpr': typeof AuthenticatedAdminGdprRoute
  '/admin/orphan-sms': typeof AuthenticatedAdminOrphanSmsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/sms-debug': typeof AuthenticatedAdminSmsDebugRoute
  '/admin/stage-rules': typeof AuthenticatedAdminStageRulesRoute
  '/admin/test-lead-intake': typeof AuthenticatedAdminTestLeadIntakeRoute
  '/installningar/profil': typeof AuthenticatedInstallningarProfilRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads/ny': typeof AuthenticatedLeadsNyRoute
  '/dealer/cars/$leadId': typeof DealerCarsLeadIdRoute
  '/admin/dealers/$dealerId': typeof AuthenticatedAdminDealersDealerIdRoute
  '/admin/fakturering/lagg-till': typeof AuthenticatedAdminFaktureringLaggTillRoute
  '/admin/match-preview/$leadId': typeof AuthenticatedAdminMatchPreviewLeadIdRoute
  '/admin/settings/billing': typeof AuthenticatedAdminSettingsBillingRoute
  '/admin/settings/external-links': typeof AuthenticatedAdminSettingsExternalLinksRoute
  '/admin/settings/followups': typeof AuthenticatedAdminSettingsFollowupsRoute
  '/admin/settings/lead-score': typeof AuthenticatedAdminSettingsLeadScoreRoute
  '/admin/settings/notifications': typeof AuthenticatedAdminSettingsNotificationsRoute
  '/admin/settings/sla': typeof AuthenticatedAdminSettingsSlaRoute
  '/admin/settings/sms-templates': typeof AuthenticatedAdminSettingsSmsTemplatesRoute
  '/admin/settings/timing': typeof AuthenticatedAdminSettingsTimingRoute
  '/rapporter/handlare/$dealerId': typeof AuthenticatedRapporterHandlareDealerIdRoute
  '/rapporter/saljare/$userId': typeof AuthenticatedRapporterSaljareUserIdRoute
  '/api/public/hooks/check-due-tasks': typeof ApiPublicHooksCheckDueTasksRoute
  '/api/public/hooks/process-queued-sms': typeof ApiPublicHooksProcessQueuedSmsRoute
  '/api/public/hooks/process-stage-jobs': typeof ApiPublicHooksProcessStageJobsRoute
  '/api/public/leads/$leadId': typeof ApiPublicLeadsLeadIdRoute
  '/api/public/leads/intake': typeof ApiPublicLeadsIntakeRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dealer': typeof DealerRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/inkorg': typeof AuthenticatedInkorgRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/rapporter': typeof AuthenticatedRapporterRouteWithChildren
  '/dealer/active': typeof DealerActiveRoute
  '/dealer/bids': typeof DealerBidsRoute
  '/dealer/won': typeof DealerWonRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/data-cleanup': typeof AuthenticatedAdminDataCleanupRoute
  '/_authenticated/admin/dealers': typeof AuthenticatedAdminDealersRouteWithChildren
  '/_authenticated/admin/exports': typeof AuthenticatedAdminExportsRoute
  '/_authenticated/admin/fakturering': typeof AuthenticatedAdminFaktureringRouteWithChildren
  '/_authenticated/admin/gdpr': typeof AuthenticatedAdminGdprRoute
  '/_authenticated/admin/orphan-sms': typeof AuthenticatedAdminOrphanSmsRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/sms-debug': typeof AuthenticatedAdminSmsDebugRoute
  '/_authenticated/admin/stage-rules': typeof AuthenticatedAdminStageRulesRoute
  '/_authenticated/admin/test-lead-intake': typeof AuthenticatedAdminTestLeadIntakeRoute
  '/_authenticated/installningar/profil': typeof AuthenticatedInstallningarProfilRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/leads/ny': typeof AuthenticatedLeadsNyRoute
  '/dealer/cars/$leadId': typeof DealerCarsLeadIdRoute
  '/_authenticated/admin/dealers/$dealerId': typeof AuthenticatedAdminDealersDealerIdRoute
  '/_authenticated/admin/fakturering/lagg-till': typeof AuthenticatedAdminFaktureringLaggTillRoute
  '/_authenticated/admin/match-preview/$leadId': typeof AuthenticatedAdminMatchPreviewLeadIdRoute
  '/_authenticated/admin/settings/billing': typeof AuthenticatedAdminSettingsBillingRoute
  '/_authenticated/admin/settings/external-links': typeof AuthenticatedAdminSettingsExternalLinksRoute
  '/_authenticated/admin/settings/followups': typeof AuthenticatedAdminSettingsFollowupsRoute
  '/_authenticated/admin/settings/lead-score': typeof AuthenticatedAdminSettingsLeadScoreRoute
  '/_authenticated/admin/settings/notifications': typeof AuthenticatedAdminSettingsNotificationsRoute
  '/_authenticated/admin/settings/sla': typeof AuthenticatedAdminSettingsSlaRoute
  '/_authenticated/admin/settings/sms-templates': typeof AuthenticatedAdminSettingsSmsTemplatesRoute
  '/_authenticated/admin/settings/timing': typeof AuthenticatedAdminSettingsTimingRoute
  '/_authenticated/rapporter/handlare/$dealerId': typeof AuthenticatedRapporterHandlareDealerIdRoute
  '/_authenticated/rapporter/saljare/$userId': typeof AuthenticatedRapporterSaljareUserIdRoute
  '/api/public/hooks/check-due-tasks': typeof ApiPublicHooksCheckDueTasksRoute
  '/api/public/hooks/process-queued-sms': typeof ApiPublicHooksProcessQueuedSmsRoute
  '/api/public/hooks/process-stage-jobs': typeof ApiPublicHooksProcessStageJobsRoute
  '/api/public/leads/$leadId': typeof ApiPublicLeadsLeadIdRoute
  '/api/public/leads/intake': typeof ApiPublicLeadsIntakeRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dealer'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/inkorg'
    | '/kalender'
    | '/rapporter'
    | '/dealer/active'
    | '/dealer/bids'
    | '/dealer/won'
    | '/dealer/'
    | '/admin/audit'
    | '/admin/data-cleanup'
    | '/admin/dealers'
    | '/admin/exports'
    | '/admin/fakturering'
    | '/admin/gdpr'
    | '/admin/orphan-sms'
    | '/admin/permissions'
    | '/admin/security'
    | '/admin/sms-debug'
    | '/admin/stage-rules'
    | '/admin/test-lead-intake'
    | '/installningar/profil'
    | '/leads/$leadId'
    | '/leads/ny'
    | '/dealer/cars/$leadId'
    | '/admin/dealers/$dealerId'
    | '/admin/fakturering/lagg-till'
    | '/admin/match-preview/$leadId'
    | '/admin/settings/billing'
    | '/admin/settings/external-links'
    | '/admin/settings/followups'
    | '/admin/settings/lead-score'
    | '/admin/settings/notifications'
    | '/admin/settings/sla'
    | '/admin/settings/sms-templates'
    | '/admin/settings/timing'
    | '/rapporter/handlare/$dealerId'
    | '/rapporter/saljare/$userId'
    | '/api/public/hooks/check-due-tasks'
    | '/api/public/hooks/process-queued-sms'
    | '/api/public/hooks/process-stage-jobs'
    | '/api/public/leads/$leadId'
    | '/api/public/leads/intake'
    | '/api/public/twilio/inbound'
    | '/api/public/twilio/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/inkorg'
    | '/kalender'
    | '/rapporter'
    | '/dealer/active'
    | '/dealer/bids'
    | '/dealer/won'
    | '/'
    | '/dealer'
    | '/admin/audit'
    | '/admin/data-cleanup'
    | '/admin/dealers'
    | '/admin/exports'
    | '/admin/fakturering'
    | '/admin/gdpr'
    | '/admin/orphan-sms'
    | '/admin/permissions'
    | '/admin/security'
    | '/admin/sms-debug'
    | '/admin/stage-rules'
    | '/admin/test-lead-intake'
    | '/installningar/profil'
    | '/leads/$leadId'
    | '/leads/ny'
    | '/dealer/cars/$leadId'
    | '/admin/dealers/$dealerId'
    | '/admin/fakturering/lagg-till'
    | '/admin/match-preview/$leadId'
    | '/admin/settings/billing'
    | '/admin/settings/external-links'
    | '/admin/settings/followups'
    | '/admin/settings/lead-score'
    | '/admin/settings/notifications'
    | '/admin/settings/sla'
    | '/admin/settings/sms-templates'
    | '/admin/settings/timing'
    | '/rapporter/handlare/$dealerId'
    | '/rapporter/saljare/$userId'
    | '/api/public/hooks/check-due-tasks'
    | '/api/public/hooks/process-queued-sms'
    | '/api/public/hooks/process-stage-jobs'
    | '/api/public/leads/$leadId'
    | '/api/public/leads/intake'
    | '/api/public/twilio/inbound'
    | '/api/public/twilio/status'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dealer'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/inkorg'
    | '/_authenticated/kalender'
    | '/_authenticated/rapporter'
    | '/dealer/active'
    | '/dealer/bids'
    | '/dealer/won'
    | '/_authenticated/'
    | '/dealer/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/data-cleanup'
    | '/_authenticated/admin/dealers'
    | '/_authenticated/admin/exports'
    | '/_authenticated/admin/fakturering'
    | '/_authenticated/admin/gdpr'
    | '/_authenticated/admin/orphan-sms'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/sms-debug'
    | '/_authenticated/admin/stage-rules'
    | '/_authenticated/admin/test-lead-intake'
    | '/_authenticated/installningar/profil'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/leads/ny'
    | '/dealer/cars/$leadId'
    | '/_authenticated/admin/dealers/$dealerId'
    | '/_authenticated/admin/fakturering/lagg-till'
    | '/_authenticated/admin/match-preview/$leadId'
    | '/_authenticated/admin/settings/billing'
    | '/_authenticated/admin/settings/external-links'
    | '/_authenticated/admin/settings/followups'
    | '/_authenticated/admin/settings/lead-score'
    | '/_authenticated/admin/settings/notifications'
    | '/_authenticated/admin/settings/sla'
    | '/_authenticated/admin/settings/sms-templates'
    | '/_authenticated/admin/settings/timing'
    | '/_authenticated/rapporter/handlare/$dealerId'
    | '/_authenticated/rapporter/saljare/$userId'
    | '/api/public/hooks/check-due-tasks'
    | '/api/public/hooks/process-queued-sms'
    | '/api/public/hooks/process-stage-jobs'
    | '/api/public/leads/$leadId'
    | '/api/public/leads/intake'
    | '/api/public/twilio/inbound'
    | '/api/public/twilio/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DealerRoute: typeof DealerRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksCheckDueTasksRoute: typeof ApiPublicHooksCheckDueTasksRoute
  ApiPublicHooksProcessQueuedSmsRoute: typeof ApiPublicHooksProcessQueuedSmsRoute
  ApiPublicHooksProcessStageJobsRoute: typeof ApiPublicHooksProcessStageJobsRoute
  ApiPublicLeadsLeadIdRoute: typeof ApiPublicLeadsLeadIdRoute
  ApiPublicLeadsIntakeRoute: typeof ApiPublicLeadsIntakeRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer': {
      id: '/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof DealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/': {
      id: '/dealer/'
      path: '/'
      fullPath: '/dealer/'
      preLoaderRoute: typeof DealerIndexRouteImport
      parentRoute: typeof DealerRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/dealer/won': {
      id: '/dealer/won'
      path: '/won'
      fullPath: '/dealer/won'
      preLoaderRoute: typeof DealerWonRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/bids': {
      id: '/dealer/bids'
      path: '/bids'
      fullPath: '/dealer/bids'
      preLoaderRoute: typeof DealerBidsRouteImport
      parentRoute: typeof DealerRoute
    }
    '/dealer/active': {
      id: '/dealer/active'
      path: '/active'
      fullPath: '/dealer/active'
      preLoaderRoute: typeof DealerActiveRouteImport
      parentRoute: typeof DealerRoute
    }
    '/_authenticated/rapporter': {
      id: '/_authenticated/rapporter'
      path: '/rapporter'
      fullPath: '/rapporter'
      preLoaderRoute: typeof AuthenticatedRapporterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inkorg': {
      id: '/_authenticated/inkorg'
      path: '/inkorg'
      fullPath: '/inkorg'
      preLoaderRoute: typeof AuthenticatedInkorgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/dealer/cars/$leadId': {
      id: '/dealer/cars/$leadId'
      path: '/cars/$leadId'
      fullPath: '/dealer/cars/$leadId'
      preLoaderRoute: typeof DealerCarsLeadIdRouteImport
      parentRoute: typeof DealerRoute
    }
    '/_authenticated/leads/ny': {
      id: '/_authenticated/leads/ny'
      path: '/leads/ny'
      fullPath: '/leads/ny'
      preLoaderRoute: typeof AuthenticatedLeadsNyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/installningar/profil': {
      id: '/_authenticated/installningar/profil'
      path: '/installningar/profil'
      fullPath: '/installningar/profil'
      preLoaderRoute: typeof AuthenticatedInstallningarProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/test-lead-intake': {
      id: '/_authenticated/admin/test-lead-intake'
      path: '/test-lead-intake'
      fullPath: '/admin/test-lead-intake'
      preLoaderRoute: typeof AuthenticatedAdminTestLeadIntakeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stage-rules': {
      id: '/_authenticated/admin/stage-rules'
      path: '/stage-rules'
      fullPath: '/admin/stage-rules'
      preLoaderRoute: typeof AuthenticatedAdminStageRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sms-debug': {
      id: '/_authenticated/admin/sms-debug'
      path: '/sms-debug'
      fullPath: '/admin/sms-debug'
      preLoaderRoute: typeof AuthenticatedAdminSmsDebugRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orphan-sms': {
      id: '/_authenticated/admin/orphan-sms'
      path: '/orphan-sms'
      fullPath: '/admin/orphan-sms'
      preLoaderRoute: typeof AuthenticatedAdminOrphanSmsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gdpr': {
      id: '/_authenticated/admin/gdpr'
      path: '/gdpr'
      fullPath: '/admin/gdpr'
      preLoaderRoute: typeof AuthenticatedAdminGdprRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fakturering': {
      id: '/_authenticated/admin/fakturering'
      path: '/fakturering'
      fullPath: '/admin/fakturering'
      preLoaderRoute: typeof AuthenticatedAdminFaktureringRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exports': {
      id: '/_authenticated/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AuthenticatedAdminExportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dealers': {
      id: '/_authenticated/admin/dealers'
      path: '/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AuthenticatedAdminDealersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/data-cleanup': {
      id: '/_authenticated/admin/data-cleanup'
      path: '/data-cleanup'
      fullPath: '/admin/data-cleanup'
      preLoaderRoute: typeof AuthenticatedAdminDataCleanupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/inbound': {
      id: '/api/public/twilio/inbound'
      path: '/api/public/twilio/inbound'
      fullPath: '/api/public/twilio/inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/intake': {
      id: '/api/public/leads/intake'
      path: '/api/public/leads/intake'
      fullPath: '/api/public/leads/intake'
      preLoaderRoute: typeof ApiPublicLeadsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/$leadId': {
      id: '/api/public/leads/$leadId'
      path: '/api/public/leads/$leadId'
      fullPath: '/api/public/leads/$leadId'
      preLoaderRoute: typeof ApiPublicLeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-stage-jobs': {
      id: '/api/public/hooks/process-stage-jobs'
      path: '/api/public/hooks/process-stage-jobs'
      fullPath: '/api/public/hooks/process-stage-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessStageJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-queued-sms': {
      id: '/api/public/hooks/process-queued-sms'
      path: '/api/public/hooks/process-queued-sms'
      fullPath: '/api/public/hooks/process-queued-sms'
      preLoaderRoute: typeof ApiPublicHooksProcessQueuedSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-due-tasks': {
      id: '/api/public/hooks/check-due-tasks'
      path: '/api/public/hooks/check-due-tasks'
      fullPath: '/api/public/hooks/check-due-tasks'
      preLoaderRoute: typeof ApiPublicHooksCheckDueTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rapporter/saljare/$userId': {
      id: '/_authenticated/rapporter/saljare/$userId'
      path: '/saljare/$userId'
      fullPath: '/rapporter/saljare/$userId'
      preLoaderRoute: typeof AuthenticatedRapporterSaljareUserIdRouteImport
      parentRoute: typeof AuthenticatedRapporterRoute
    }
    '/_authenticated/rapporter/handlare/$dealerId': {
      id: '/_authenticated/rapporter/handlare/$dealerId'
      path: '/handlare/$dealerId'
      fullPath: '/rapporter/handlare/$dealerId'
      preLoaderRoute: typeof AuthenticatedRapporterHandlareDealerIdRouteImport
      parentRoute: typeof AuthenticatedRapporterRoute
    }
    '/_authenticated/admin/settings/timing': {
      id: '/_authenticated/admin/settings/timing'
      path: '/settings/timing'
      fullPath: '/admin/settings/timing'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTimingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/sms-templates': {
      id: '/_authenticated/admin/settings/sms-templates'
      path: '/settings/sms-templates'
      fullPath: '/admin/settings/sms-templates'
      preLoaderRoute: typeof AuthenticatedAdminSettingsSmsTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/sla': {
      id: '/_authenticated/admin/settings/sla'
      path: '/settings/sla'
      fullPath: '/admin/settings/sla'
      preLoaderRoute: typeof AuthenticatedAdminSettingsSlaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/notifications': {
      id: '/_authenticated/admin/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAdminSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/lead-score': {
      id: '/_authenticated/admin/settings/lead-score'
      path: '/settings/lead-score'
      fullPath: '/admin/settings/lead-score'
      preLoaderRoute: typeof AuthenticatedAdminSettingsLeadScoreRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/followups': {
      id: '/_authenticated/admin/settings/followups'
      path: '/settings/followups'
      fullPath: '/admin/settings/followups'
      preLoaderRoute: typeof AuthenticatedAdminSettingsFollowupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/external-links': {
      id: '/_authenticated/admin/settings/external-links'
      path: '/settings/external-links'
      fullPath: '/admin/settings/external-links'
      preLoaderRoute: typeof AuthenticatedAdminSettingsExternalLinksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/billing': {
      id: '/_authenticated/admin/settings/billing'
      path: '/settings/billing'
      fullPath: '/admin/settings/billing'
      preLoaderRoute: typeof AuthenticatedAdminSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/match-preview/$leadId': {
      id: '/_authenticated/admin/match-preview/$leadId'
      path: '/match-preview/$leadId'
      fullPath: '/admin/match-preview/$leadId'
      preLoaderRoute: typeof AuthenticatedAdminMatchPreviewLeadIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/fakturering/lagg-till': {
      id: '/_authenticated/admin/fakturering/lagg-till'
      path: '/lagg-till'
      fullPath: '/admin/fakturering/lagg-till'
      preLoaderRoute: typeof AuthenticatedAdminFaktureringLaggTillRouteImport
      parentRoute: typeof AuthenticatedAdminFaktureringRoute
    }
    '/_authenticated/admin/dealers/$dealerId': {
      id: '/_authenticated/admin/dealers/$dealerId'
      path: '/$dealerId'
      fullPath: '/admin/dealers/$dealerId'
      preLoaderRoute: typeof AuthenticatedAdminDealersDealerIdRouteImport
      parentRoute: typeof AuthenticatedAdminDealersRoute
    }
  }
}

interface AuthenticatedAdminDealersRouteChildren {
  AuthenticatedAdminDealersDealerIdRoute: typeof AuthenticatedAdminDealersDealerIdRoute
}

const AuthenticatedAdminDealersRouteChildren: AuthenticatedAdminDealersRouteChildren =
  {
    AuthenticatedAdminDealersDealerIdRoute:
      AuthenticatedAdminDealersDealerIdRoute,
  }

const AuthenticatedAdminDealersRouteWithChildren =
  AuthenticatedAdminDealersRoute._addFileChildren(
    AuthenticatedAdminDealersRouteChildren,
  )

interface AuthenticatedAdminFaktureringRouteChildren {
  AuthenticatedAdminFaktureringLaggTillRoute: typeof AuthenticatedAdminFaktureringLaggTillRoute
}

const AuthenticatedAdminFaktureringRouteChildren: AuthenticatedAdminFaktureringRouteChildren =
  {
    AuthenticatedAdminFaktureringLaggTillRoute:
      AuthenticatedAdminFaktureringLaggTillRoute,
  }

const AuthenticatedAdminFaktureringRouteWithChildren =
  AuthenticatedAdminFaktureringRoute._addFileChildren(
    AuthenticatedAdminFaktureringRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDataCleanupRoute: typeof AuthenticatedAdminDataCleanupRoute
  AuthenticatedAdminDealersRoute: typeof AuthenticatedAdminDealersRouteWithChildren
  AuthenticatedAdminExportsRoute: typeof AuthenticatedAdminExportsRoute
  AuthenticatedAdminFaktureringRoute: typeof AuthenticatedAdminFaktureringRouteWithChildren
  AuthenticatedAdminGdprRoute: typeof AuthenticatedAdminGdprRoute
  AuthenticatedAdminOrphanSmsRoute: typeof AuthenticatedAdminOrphanSmsRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSmsDebugRoute: typeof AuthenticatedAdminSmsDebugRoute
  AuthenticatedAdminStageRulesRoute: typeof AuthenticatedAdminStageRulesRoute
  AuthenticatedAdminTestLeadIntakeRoute: typeof AuthenticatedAdminTestLeadIntakeRoute
  AuthenticatedAdminMatchPreviewLeadIdRoute: typeof AuthenticatedAdminMatchPreviewLeadIdRoute
  AuthenticatedAdminSettingsBillingRoute: typeof AuthenticatedAdminSettingsBillingRoute
  AuthenticatedAdminSettingsExternalLinksRoute: typeof AuthenticatedAdminSettingsExternalLinksRoute
  AuthenticatedAdminSettingsFollowupsRoute: typeof AuthenticatedAdminSettingsFollowupsRoute
  AuthenticatedAdminSettingsLeadScoreRoute: typeof AuthenticatedAdminSettingsLeadScoreRoute
  AuthenticatedAdminSettingsNotificationsRoute: typeof AuthenticatedAdminSettingsNotificationsRoute
  AuthenticatedAdminSettingsSlaRoute: typeof AuthenticatedAdminSettingsSlaRoute
  AuthenticatedAdminSettingsSmsTemplatesRoute: typeof AuthenticatedAdminSettingsSmsTemplatesRoute
  AuthenticatedAdminSettingsTimingRoute: typeof AuthenticatedAdminSettingsTimingRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminDataCleanupRoute: AuthenticatedAdminDataCleanupRoute,
    AuthenticatedAdminDealersRoute: AuthenticatedAdminDealersRouteWithChildren,
    AuthenticatedAdminExportsRoute: AuthenticatedAdminExportsRoute,
    AuthenticatedAdminFaktureringRoute:
      AuthenticatedAdminFaktureringRouteWithChildren,
    AuthenticatedAdminGdprRoute: AuthenticatedAdminGdprRoute,
    AuthenticatedAdminOrphanSmsRoute: AuthenticatedAdminOrphanSmsRoute,
    AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
    AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
    AuthenticatedAdminSmsDebugRoute: AuthenticatedAdminSmsDebugRoute,
    AuthenticatedAdminStageRulesRoute: AuthenticatedAdminStageRulesRoute,
    AuthenticatedAdminTestLeadIntakeRoute:
      AuthenticatedAdminTestLeadIntakeRoute,
    AuthenticatedAdminMatchPreviewLeadIdRoute:
      AuthenticatedAdminMatchPreviewLeadIdRoute,
    AuthenticatedAdminSettingsBillingRoute:
      AuthenticatedAdminSettingsBillingRoute,
    AuthenticatedAdminSettingsExternalLinksRoute:
      AuthenticatedAdminSettingsExternalLinksRoute,
    AuthenticatedAdminSettingsFollowupsRoute:
      AuthenticatedAdminSettingsFollowupsRoute,
    AuthenticatedAdminSettingsLeadScoreRoute:
      AuthenticatedAdminSettingsLeadScoreRoute,
    AuthenticatedAdminSettingsNotificationsRoute:
      AuthenticatedAdminSettingsNotificationsRoute,
    AuthenticatedAdminSettingsSlaRoute: AuthenticatedAdminSettingsSlaRoute,
    AuthenticatedAdminSettingsSmsTemplatesRoute:
      AuthenticatedAdminSettingsSmsTemplatesRoute,
    AuthenticatedAdminSettingsTimingRoute:
      AuthenticatedAdminSettingsTimingRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRapporterRouteChildren {
  AuthenticatedRapporterHandlareDealerIdRoute: typeof AuthenticatedRapporterHandlareDealerIdRoute
  AuthenticatedRapporterSaljareUserIdRoute: typeof AuthenticatedRapporterSaljareUserIdRoute
}

const AuthenticatedRapporterRouteChildren: AuthenticatedRapporterRouteChildren =
  {
    AuthenticatedRapporterHandlareDealerIdRoute:
      AuthenticatedRapporterHandlareDealerIdRoute,
    AuthenticatedRapporterSaljareUserIdRoute:
      AuthenticatedRapporterSaljareUserIdRoute,
  }

const AuthenticatedRapporterRouteWithChildren =
  AuthenticatedRapporterRoute._addFileChildren(
    AuthenticatedRapporterRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedInkorgRoute: typeof AuthenticatedInkorgRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedRapporterRoute: typeof AuthenticatedRapporterRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInstallningarProfilRoute: typeof AuthenticatedInstallningarProfilRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedLeadsNyRoute: typeof AuthenticatedLeadsNyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedInkorgRoute: AuthenticatedInkorgRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedRapporterRoute: AuthenticatedRapporterRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInstallningarProfilRoute: AuthenticatedInstallningarProfilRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedLeadsNyRoute: AuthenticatedLeadsNyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DealerRouteChildren {
  DealerActiveRoute: typeof DealerActiveRoute
  DealerBidsRoute: typeof DealerBidsRoute
  DealerWonRoute: typeof DealerWonRoute
  DealerIndexRoute: typeof DealerIndexRoute
  DealerCarsLeadIdRoute: typeof DealerCarsLeadIdRoute
}

const DealerRouteChildren: DealerRouteChildren = {
  DealerActiveRoute: DealerActiveRoute,
  DealerBidsRoute: DealerBidsRoute,
  DealerWonRoute: DealerWonRoute,
  DealerIndexRoute: DealerIndexRoute,
  DealerCarsLeadIdRoute: DealerCarsLeadIdRoute,
}

const DealerRouteWithChildren =
  DealerRoute._addFileChildren(DealerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DealerRoute: DealerRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksCheckDueTasksRoute: ApiPublicHooksCheckDueTasksRoute,
  ApiPublicHooksProcessQueuedSmsRoute: ApiPublicHooksProcessQueuedSmsRoute,
  ApiPublicHooksProcessStageJobsRoute: ApiPublicHooksProcessStageJobsRoute,
  ApiPublicLeadsLeadIdRoute: ApiPublicLeadsLeadIdRoute,
  ApiPublicLeadsIntakeRoute: ApiPublicLeadsIntakeRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
